### ISSUE TITLE
Missing POM for 0.2

### ISSUE THREAD

**Issue by nightscape** [47deg/macroid-extras#32]
Hi 47deg people :)

Version 0.2 is missing the POM:
http://jcenter.bintray.com/com/fortysevendeg/macroid-extras_2.11/0.2/
Version 0.1.1 does have it:
http://jcenter.bintray.com/com/fortysevendeg/macroid-extras_2.11/0.1.1/
Did something change in the release process?

Best
  Martin

**Comment by nightscape** [comment]
Bump :)

**Comment by fedefernandez** [comment]
Hi @nightscape the issue has been resolved. Thanks for the advice and sorry for the delay.

Best
Fede
