### ISSUE TITLE
How do we set attribute with question mark?

### ISSUE THREAD

**Issue by wpoosanguansit** [47deg/macroid-extras#33]
Hi,

I am looking through the code for example and I would appreciate if you can point me to any for setting the values as below:

  //        android:layout_height="?attr/actionBarSize"
  //        android:background="?attr/colorPrimary"
  //        app:popupTheme="@style/ThemeOverlay.AppCompat.Light"
  //        app:layout_scrollFlags="scroll | enterAlways" />

Specifically for ? and |.  Thanks for your help.

**Comment by javipacheco** [comment]
@wpoosanguansit Sorry for delay

I think that you want to change the *ToolBar*. We made the similar thing in Scala Days App, you can see the [code here](https://github.com/47deg/scala-days-android/blob/master/src/main/scala/com/fortysevendeg/android/scaladays/ui/commons/ToolbarLayout.scala#L52) 

If you want to get the resourceId from an attribute you can use the next function:

```
def attrId() = {
    val tv: TypedValue = new TypedValue
    contextWrapper.application.getTheme.resolveAttribute(android.R.attr.actionBarSize, tv, true)
    tv.resourceId
  }
```

It's very important the theme that you are using to find the appropriate resource. If you are using a different theme in your Activity, for example, you should use `activityContextWrapper.getOriginal.getTheme`. Remember, you are looking for an attribute in the selected theme

I think that we can add this methods in `ResourcesUtils` in the next version of `macroid-extras`

The last question about `scroll` and `|`, you can create a new Tweak like:

```
  def scrollFlag(flags: Int) = Tweak[AppBarLayout] {
    view =>
      view.getLayoutParams match {
        case lp: AppBarLayout.LayoutParams =>
          lp.setScrollFlags(flags)
      }
  }

  ....

  toolbar <~ scrollFlag(AppBarLayout.LayoutParams.SCROLL_FLAG_SCROLL | AppBarLayout.LayoutParams.SCROLL_FLAG_ENTER_ALWAYS)

```

I hope that this comment can help you. Please let me know if you have any questions

**Comment by wpoosanguansit** [comment]
Thank you.
