### ISSUE TITLE
Setting Margin on TextView crashes the app with class cast exception

### ISSUE THREAD

**Issue by pamu** [47deg/macroid-extras#35]
setting `vMargins(resGetDimensionPixelSize(R.dimen.padding_default_large)) ` on the text view crashing the app with class cast exception.

**Comment by javipacheco** [comment]
Hi @pamu 

The margin is related to the view's container. It's possible that you have to use another `Tweak` 

For example, if your `TextView` is contained in a `LinearLayout` you should use `llLayoutMargin` or if is in a `FrameLayout` you should use `flLayoutMargin`

The `LayoutParams` of your container should extend from `MarginLayoutParams` and that I'm almost sure that this is the error

I hope that this helps you

**Comment by pamu** [comment]
Thanks
