### ISSUE TITLE
Context wrapper

### ISSUE THREAD

**Issue by rutaihwa** [47deg/macroid-extras#39]
Am I missing something or the latest version of macroid don't support ContextWrapper anymore while the current of macroid-extras still make use of them [as example here.](https://github.com/47deg/macroid-extras/blob/master/src/main/scala/com/fortysevendeg/macroid/extras/TweaksExtras.scala#L42)?

**Comment by javipacheco** [comment]
The last version of macroid supports [ContextWrapper](https://github.com/47deg/macroid/blob/master/macroid-core/src/main/scala/macroid/Contexts.scala#L18)

What's your problem? What version of macroid are you using?

**Comment by rutaihwa** [comment]
@javipacheco I know how dumb the question have been, my fault. The thing is that I noticed that macroid support ContextWrapper but my version of macroid-extras still uses ApplicationContextWrapper I now think I should move to the latest snapshot of macroid-extras which uses ContextWrapper which is I guess is the version corresponding to the repo. I'm using macroid 2.0.0-M4 and macroid-extras 0.2.
